# 使用个人腾讯云镜像仓库，自动构建镜像并将其部署到 Docker Swarm。

# 变量定义
variables:
  # 你的个人镜像仓库地址
  IMAGE_REPOSITORY_URL: "ccr.ccs.tencentyun.com/xxxxxx/gitlab"
  # 你的 Docker Swarm 服务栈名称
  SWARM_STACK_NAME: "gitlab-stack"
  # 腾讯云容器镜像服务的登录地址
  REGISTRY_HOST: "ccr.ccs.tencentyun.com"

stages:
  - build
  - deploy

build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    # 禁用 Docker 的 TLS 连接
    DOCKER_TLS_CERTDIR: ""
    DOCKER_BUILDKIT: "1"

  script:
    # 1. 使用你的镜像仓库地址和唯一的 Commit SHA 作为标签，构建 Docker 镜像
    - docker build -t ${IMAGE_REPOSITORY_URL}:${CI_COMMIT_SHA} .
    # 2. 登录到腾讯云镜像服务
    - docker login -u $TENCENT_CLOUD_ACCOUNT_ID -p $REGISTRY_PASSWORD $REGISTRY_HOST
    # 3. 将构建好的镜像推送到你的个人仓库
    - docker push ${IMAGE_REPOSITORY_URL}:${CI_COMMIT_SHA}
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy:
  stage: deploy
  image: docker:latest
  before_script:
    - "which ssh-agent || ( apk add --update openssh-client )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $SWARM_MANAGER_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "正在通过 SSH 管道部署 docker-compose.yml..."
    # 使用 'cat' 读取本地的 docker-compose.yml 文件，
    # 并通过管道 '|' 将其内容作为标准输入传递给 ssh 远程命令。
    - |
      cat docker-compose.yml | ssh ${SWARM_MANAGER_USER}@${SWARM_MANAGER_HOST} "
        echo '--- 正在登录镜像仓库 ---' &&
        docker login -u ${TENCENT_CLOUD_ACCOUNT_ID} -p '${REGISTRY_PASSWORD}' ${REGISTRY_HOST} &&

        echo '--- 正在部署/更新服务栈 ---' &&
        # 将镜像仓库地址和标签作为环境变量，传递给 docker stack deploy 命令
        export IMAGE_URL=${IMAGE_REPOSITORY_URL} &&
        export IMAGE_TAG=${CI_COMMIT_SHA} &&
        docker stack deploy \
          -c - \
          --with-registry-auth \
          ${SWARM_STACK_NAME} &&

        echo '--- 部署完成 ---' &&
        docker service ls
      "
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
